url: https://illperipherals.github.io
baseurl: 

# Site settings
title: illperipherals
email: travis.teague@gmail.com
description: "Welcome to illperipherals."


# Team names, titles and social links
people:
- name: Travis L. Teague
  pic: 1
  position: Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/
  - title: github
    url: http://github.com/illperipherals

# Postal address (add as many lines as necessary)
address:
  - line: Texas

# Build settings
markdown: kramdown
permalink: pretty
